### ISSUE TITLE
I know this hasn't had any pushes for a while - would you consider releasing this on Curse?

### ISSUE THREAD

**Issue by kil0byt3** [Lonami/LogImmune#1]
Hi there! I'm a developer for the pack [Rebirth of the Night.](https://www.curseforge.com/minecraft/modpacks/rebirth-of-the-night) I'd love to include this mod in the pack rather than ESM's idea of the same thing (your mod is far better at preventing cheesing from jumping off cliffs, etc), but it needs to be on Curse to add to modpacks - would you consider releasing this there?

**Comment by Lonami** [comment]
Haha I can't believe people actually found this (and found it useful even). I don't have any intentions on keeping it up-to-date with more recent Forge versions but if that's okay I wouldn't mind adding this to Curse.

**Comment by kil0byt3** [comment]
Haha! I had Googled "login resistance mod minecraft" in an attempt to try to find a better way of implementing the Epic Siege resistance on login feature - the admin for one of our community servers was looking for something to prevent their players from cheesing the ESM resistance. Your mod was result #3 in google! 

Glad I found it, and that you're willing - we're totally fine with not upgrading to more recent versions of Forge, we'll be on 1.12 for a while. I've already tested your mod and it works great for our pack in its current form, so if you could add it to Curse and we could include it officially in the pack, that would be incredible!

**Comment by Lonami** [comment]
Here's the CurseForge URL: https://www.curseforge.com/minecraft/mc-mods/logimmune

Should become available after a moderator reviews it:
> This is a new project. Until approved by a moderator, the project will not be visible to others, and its files will not synchronize across CurseForge.

**Comment by kil0byt3** [comment]
Amazing, thank you!
